//Symbol for commands
const MOVIEAPP_CMD_CACHEMOVIES = Symbol.for('MOVIEAPP_CMD_CACHEMOVIES');
const MOVIEAPP_CMD_FETCHMOVIEMETA = Symbol.for('MOVIEAPP_CMD_FETCHMOVIEMETA');
const MOVIEAPP_CMD_FETCHSUGGESTIONS = Symbol.for('MOVIEAPP_CMD_FETCHSUGGESTIONS');
const MOVIEAPP_CMD_FETCHRECOMMENDEDMOVIESMETA = Symbol.for('MOVIEAPP_CMD_FETCHRECOMMENDEDMOVIESMETA');

const MOVIEAPP_CMD_UNKNOWN = Symbol.for('MOVIEAPP_CMD_UNKNOWN');


//Symbols for command results
const MOVIEAPP_CMD_RESULT_OK = Symbol.for('MOVIEAPP_CMD_RESULT_OK');
const MOVIEAPP_CMD_RESULT_FAILED = Symbol.for('MOVIEAPP_CMD_RESULT_FAILED');


//Symbols for CACHE
const MOVIEAPP_CACHE_ALLMOVIES  = Symbol.for('MOVIEAPP_CACHE_ALLMOVIES');

//Log levels
const LOGLEVELS = {
        NONE:  'NONE',
        ERROR: 'ERROR',
        INFO:  'INFO',
        DEBUG: 'DEBUG'
    };